version: 2
jobs:
  build:
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Grab dependencies
          command: |
            which node
            node -v
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs
            nvm use 10
            node -v
      - run:
          name: Build application Docker image
          command: |
            docker build -t buildshuttle .
      - run:
          name: Run tests
          command: |
            node -v
            npm install
            DOCKER_BUILD_IMAGE=buildshuttle npm test
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" != "release" ]; then
              if [ "${CIRCLE_PROJECT_USERNAME}" == "akkeris" ]; then 
                docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
                docker tag buildshuttle "docker.io/akkeris/buildshuttle:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
                docker push "docker.io/akkeris/buildshuttle:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  docker tag buildshuttle "docker.io/akkeris/buildshuttle:release-${CIRCLE_BUILD_NUM}"
                  docker tag buildshuttle "docker.io/akkeris/buildshuttle:latest"
                  docker push "docker.io/akkeris/buildshuttle:latest"
                  docker push "docker.io/akkeris/buildshuttle:release-${CIRCLE_BUILD_NUM}"
                fi
              fi
            fi
