version: 2
jobs:
  build:
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: |
          node -v
      - run: |
          nvm install v10
          node -v
          nvm alias default v10
      - run: |
          node -v
      - run:
          name: Build application Docker image
          command: |
            docker build -t buildshuttle .
      - run:
          name: Run tests
          command: |
            npm install
            DOCKER_BUILD_IMAGE=buildshuttle npm test
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" != "release" ]; then
              if [ "${CIRCLE_PROJECT_USERNAME}" == "akkeris" ]; then 
                docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
                docker tag buildshuttle "docker.io/akkeris/buildshuttle:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
                docker push "docker.io/akkeris/buildshuttle:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  docker tag buildshuttle "docker.io/akkeris/buildshuttle:release-${CIRCLE_BUILD_NUM}"
                  docker tag buildshuttle "docker.io/akkeris/buildshuttle:latest"
                  docker push "docker.io/akkeris/buildshuttle:latest"
                  docker push "docker.io/akkeris/buildshuttle:release-${CIRCLE_BUILD_NUM}"
                fi
              fi
            fi
