apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: buildshuttle
    name: buildshuttle
    namespace: akkeris-system
  name: buildshuttle
  namespace: akkeris-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: buildshuttle
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: buildshuttle
        name: buildshuttle
        namespace: akkeris-system
      name: buildshuttle
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: akkeris.io/node-role
                operator: In
                values:
                - build
      containers:
      - env:
        - name: DEBUG
          value: ""
        - name: PORT
          value: "9000"
        - name: MAXIMUM_PARALLEL_BUILDS
          value: "4"
        - name: DOCKER_BUILD_IMAGE
          value: akkeris/buildshuttle:latest
        - name: DOCKER_BUILD_SETTINGS
          value: '{"host": "http://buildshuttle.akkeris-system", "port": "2375"}'
        - name: S3_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: S3_ACCESS_KEY
              name: buildshuttle
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              key: S3_BUCKET
              name: buildshuttle
        - name: S3_LOCATION
          valueFrom:
            configMapKeyRef:
              key: S3_LOCATION
              name: buildshuttle
        - name: S3_REGION
          valueFrom:
            configMapKeyRef:
              key: S3_REGION
              name: buildshuttle
        - name: S3_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: S3_SECRET_KEY
              name: buildshuttle
        image: akkeris/buildshuttle:latest
        imagePullPolicy: Always
        name: buildshuttle
        ports:
        - containerPort: 9000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
        resources: {}
        securityContext:
          capabilities: {}
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      - name: dind
        command:
        - /usr/local/bin/dockerd-entrypoint.sh
        - --max-concurrent-uploads=20
        - --max-concurrent-downloads=20
        ports:
        - containerPort: 2375
          protocol: TCP
        image: docker:18.05-dind
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
        securityContext:
          privileged: true
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: File
        name: docker-socket
      - name: dind-storage
        emptyDir: {}