apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  generation: 13
  labels:
    app: buildshuttle
    name: buildshuttle
    namespace: akkeris-system
  name: buildshuttle
  namespace: akkeris-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: buildshuttle
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: buildshuttle
        name: buildshuttle
        namespace: akkeris-system
      name: buildshuttle
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: akkeris.io/node-role
                operator: In
                values:
                - build
      containers:
      - env:
        - name: PORT
          value: "9000"
        - name: MAXIMUM_PARALLEL_BUILDS
          value: "4"
        - name: DOCKER_BUILD_IMAGE
          value: akkeris/buildshuttle:latest
        - name: S3_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: S3_ACCESS_KEY
              name: buildshuttle
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              key: S3_BUCKET
              name: buildshuttle
        - name: S3_LOCATION
          valueFrom:
            configMapKeyRef:
              key: S3_LOCATION
              name: buildshuttle
        - name: S3_REGION
          valueFrom:
            configMapKeyRef:
              key: S3_REGION
              name: buildshuttle
        - name: S3_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: S3_SECRET_KEY
              name: buildshuttle
        image: akkeris/buildshuttle:latest
        imagePullPolicy: Always
        name: buildshuttle
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
          requests:
            memory: "2Gi"
            cpu: "0.5"
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
        resources: {}
        securityContext:
          capabilities: {}
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: File
        name: docker-socket
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: buildshuttle
    name: buildshuttle
  name: buildshuttle
  namespace: akkeris-system
  selfLink: /api/v1/namespaces/akkeris-system/services/buildshuttle
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    name: buildshuttle
  sessionAffinity: None
  type: ClusterIp